// Code Generated by Sidekick is for learning and experimentation purposes only.
const fs = require('fs');
const path = require('path');

const constantsPath = path.join(__dirname, '..', 'src', 'app', 'shared', 'constants.ts'); // Adjust path if needed
const fileContent = fs.readFileSync(constantsPath, 'utf8');

const isDevMatch = fileContent.match(/IS_DEV_ENVIRONMENT\s*:\s*(true|false)/);
const isStageMatch = fileContent.match(/IS_STAGE_ENVIRONMENT\s*:\s*(true|false)/);
const isLocalDatabase = fileContent.match(/USE_LOCAL_DATABASE\s*:\s*(true|false)/);

let exit = false;
if (!isDevMatch) {
  console.error('🔴 Could not find IS_DEV_ENVIRONMENT in constants.ts');
  exit = true;
}
if (!isStageMatch) {
  console.error('🔴 Could not find IS_STAGE_ENVIRONMENT in constants.ts');
  exit = true;
}
if (!isLocalDatabase) {
  console.error('🔴 Could not find USE_LOCAL_DATABASE in constants.ts');
  exit = true;
}

if (isDevMatch[1] === 'true') {
  console.error('🔴 Staging Deployment blocked: IS_DEV_ENVIRONMENT is set to true.');
  exit = true;
} else {
  console.log('✅ IS_DEV_ENVIRONMENT is set to false.');
}
if (isStageMatch[1] === 'false') {
  console.error('🔴 Staging Deployment blocked: IS_STAGE_ENVIRONMENT is set to false.');
  exit = true;
} else {
  console.log('✅ IS_STAGE_ENVIRONMENT is set to true.');
}
if (isLocalDatabase[1] === 'true') {
  console.error('🔴 Staging Deployment blocked: USE_LOCAL_DATABASE is set to true.');
  exit = true;
} else {
  console.log('✅ USE_LOCAL_DATABASE is set to false.');
}

if (exit) {
  console.error('\n➡️  Please set IS_DEV_ENVIRONMENT, USE_LOCAL_DATABASE to false and IS_STAGE_ENVIRONMENT to true before deploying.');
  process.exit(1);
} else {
  console.log('\n✅ Staging Deployment checks passed. Proceed with deployment.');
}